domd/domu: Fix PVRUM postinstall script failure
Apply the following changes [1] when using prebuilt EVA proprietary
"graphics" packages as well (--product gen3-test).

Otherwise script fails:
WARNING: core-image-weston-1.0-r0 do_rootfs: rcar-proprietary-graphic.postinst
returned 1, marking as unpacked only, configuration required on target.
ERROR: core-image-weston-1.0-r0 do_rootfs: Postinstall scriptlets
of ['rcar-proprietary-graphic'] have failed.
If the intention is to defer them to first boot,
then please place them into pkg_postinst_ontarget_${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.

[1]
https://github.com/xen-troops/meta-xt-images/commit/9108e9f79b73c2aa190a4000a5450e95786543d4

Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>